// <auto-generated />
namespace Tales.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_summery_to_post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_summery_to_post));
        
        string IMigrationMetadata.Id
        {
            get { return "201509100504398_added_summery_to_post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
